---
name: Apache-Hadoop-WebHDFS
version: v0.3.1
author:
  - 'Adam Faris <apache-hadoop-webhdfs@mekanix.org>'
abstract: "interface to Hadoop's WebHDS API that supports GSSAPI/SPNEGO (secure) access."
license: apache
build_requires:
  Test::More: 0
requires:
  Carp: 0
  File::Map: 0
  LWP::Authen::Negotiate: 0
  LWP::Debug: 0
  WWW::Mechanize: 0
  parent: 0
  perl: 5.006
configure_requires:
  Module::Build: 0.35
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
provides:
  Apache::Hadoop::WebHDFS:
    file: lib/Apache/Hadoop/WebHDFS.pm
    version: v0.3.1
resources:
  license: http://apache.org/licenses/LICENSE-2.0
